alias edit-aliases='vim ~/.bash_aliases'
alias mysql-aj='mysql -h 127.0.0.1 -paj'
alias xampp='sudo /opt/lampp/xampp'
alias hab='brave-browser https://habitica.com && i3-msg workspace "1:🌐 Browser"'
alias cal='brave-browser https://calendar.google.com/calendar/u/0/r && i3-msg workspace "1:🌐 Browser"'
alias b='~/.local/bin/brave_i3-msg_shortcuts.sh'
